name: cd-dev

permissions:
  id-token: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-deploy-dev:
    uses: ./.github/workflows/deploy-job.yml
    with: 
      environment: dev
    secrets:
      gcp_provider_name: whatever
      gcp_sa_email: whatever
